#config_version=6

mode:
  start_events: ball_started
#  priority: 100



slide_player:
  mode_base_started: base

variable_player:
  s_alpha_1_target_active:
    score: 100
    bonus_multiplier: 1
  s_alpha_2_target_1_active:
    score: 100
    bonus_multiplier: 1
  s_alpha_2_target_2_active:
    score: 100
    bonus_multiplier: 1
  s_1_top_rollover_active:
    score: 1000