#config_version=6


coils:
  #desactiver a la fin du game
  c_game_over:
    default_pulse_ms: 200
    number: 100
  c_tilt:
    default_pulse_ms: 200
    number: 101
  c_ball_release:
    default_pulse_ms: 200
    number: 102
  #a maintenir pour activer bobine
  c_relay_s:
    number: 112
    allow_enable: true
    default_hold_power: .2
  c_relay_a:
    default_pulse_ms: 120
    number: 113
  c_stargate_ramp:
    default_pulse_ms: 120
    number: 114
  c_1:
    #S OFF 1 Bank Reset / S ON left top dome
    default_pulse_ms: 120
    number: 1
  c_2:
    #S OFF 2 Bank Reset / S ON left center dome
    default_pulse_ms: 120
    number: 2
  c_3:
    #S OFF Hole / S ON Stargate
    default_pulse_ms: 120
    number: 3
  c_5:
    #S OFF 3 Bank Reset / S ON left bottom dome
    default_pulse_ms: 120
    number: 5
  c_6:
    #S OFF 4 Bank reset / S ON Right Top Dome
    default_pulse_ms: 120
    number: 6

psus:
  default:
    voltage: 48
    release_wait_ms: 10    # defaults to 10ms
dual_wound_coils:
  c_hole_eject:
    hold_coil: c_relay_s
    main_coil: c_3


#coil_player:
#  activer_bobine_stargate:
#    c_relay_s  :
#      action: enable
#      hold_power: .5
# L0 enable Relay Q Game over
# L1 Relay T
# L2 Ball release
#L12 Relay S
#L13 Relay A
#L14 Stargate ramp

#Rel S  OFF           ON
#Sol 1     1 bank      left top dome
#Sol 2     2 bank      left center dome
#Sol 3     Hole        Stargate #67 
