#config_version=6

hardware:
  #platform: smart_virtual
  platform: lisy
lisy:
  connection: serial
  port: /dev/ttyACM0
  baud: 115200

config:
  - switches.yaml
  - coils.yaml
  - displays.yaml
  - lamps.yaml

playfields:
  playfield:
    default_source_device: bd_drain
    tags: default

digital_outputs:
    game_over_relay:
        number: 1
        type: light
        enable_events: ball_started
        disable_events: ball_will_end

game:
    balls_per_game: 3

ball_devices:
    bd_drain:
        ball_switches: s_outhole
        eject_coil: c_outhole
        eject_targets: playfield
        tags: drain, home, trough