#config_version=6

hardware:
  #platform: smart_virtual
  platform: lisy
lisy:
  connection: serial
  port: /dev/ttyACM0
  baud: 115200

modes:
  - attract
  - base
#virtual_platform_start_active_switches: s_trough

config:
  - switches.yaml
  - coils.yaml
  - displays.yaml
  - lamps.yaml
  - vars.yaml
  - targets.yaml

playfields:
  playfield:
    default_source_device: bd_plung
    tags: default



digital_outputs:
    #activation des batteurs et bumpers
    game_over_relay:
        number: 0
        type: light
        enable_events: ball_started
        disable_events: ball_will_end

game:
    balls_per_game: 3

ball_devices:
    #ejection de la bille dans le lanceur
    bd_plung:
      ball_switches: s_trough
      eject_coil: c_ball_release  
      eject_targets: playfield
      tags: home, trough
    #drain  
    bd_drain:
        ball_switches: s_outhole
        eject_coil: c_hole_eject
        eject_targets: bd_plung
        tags: drain
    
keyboard:
  debug: yes
  a:
    switch: s_start
  z:
    switch: s_trough
    invert: true 
  e:
    switch: s_shooter_lane_rollover
  r:
    switch: s_1_top_rollover
